vars:
  - data_version: ["v1", "v2"]

stages:
  download_v1:
    cmd: python scripts/download_v1.py
    deps:
      - scripts/download_v1.py
    outs:
      - data/raw/x_train_v1.npy
      - data/raw/y_train_v1.npy
      - data/raw/x_test.npy
      - data/raw/y_test.npy

  download_v2:
    cmd: python scripts/download_v2.py
    deps:
      - scripts/download_v2.py
      - data/raw/x_train_v1.npy
      - data/raw/y_train_v1.npy
    outs:
      - data/raw/x_train_v2.npy
      - data/raw/y_train_v2.npy

  train_${data_version}:
    foreach: ${data_version}
    do:
      cmd: python scripts/train.py --version ${item}
      deps:
        - scripts/train.py
        - data/raw/x_train_${item}.npy
        - data/raw/y_train_${item}.npy
        - data/raw/x_test.npy
        - data/raw/y_test.npy
      params:
        - model
      outs:
        - models/model_${item}.npy
      metrics:
        - models/metrics_${item}.json:
            cache: false
